services:
  bot:
    image: mkode312/telegram-bot-mafia:latest
    pull_policy: always
    restart: unless-stopped
    stop_grace_period: 15s
    env_file:
      - .env
    environment:
      CONFIG_PATH: /app/config/prod.yaml
      BOT_TOKEN: ${BOT_TOKEN}
    volumes:
      - /etc/mafia-bot:/app/config:ro
